"""Store protocol for persistence."""

from typing import Protocol

from app.domain.contracts import (
    ApprovalRequest,
    CommunicationUpdate,
    EvidenceItem,
    ExternalAction,
    Hypothesis,
    Incident,
    PatchAttempt,
    Postmortem,
    RemediationPlan,
    TimelineEvent,
    VerificationRun,
    WorkflowEvent,
)
from app.domain.enums import Environment, Severity, WorkflowState
from app.domain.investigation import InvestigationReport
from app.domain.remediation import ApprovalBinding, RemediationPlanArtifact
from app.domain.sandbox import PatchExecutionArtifact
from app.domain.verification import VerificationRunArtifact


class NotFoundError(Exception):
    pass


class StoreProtocol(Protocol):
    def reset(self) -> None: ...

    def next_id(self, prefix: str) -> str: ...

    def add_incident(self, incident: Incident) -> Incident: ...

    def get_incident(self, incident_id: str) -> Incident: ...

    def list_incidents(
        self,
        status: WorkflowState | None = None,
        severity: Severity | None = None,
        service: str | None = None,
        environment: Environment | None = None,
        limit: int = 50,
    ) -> list[Incident]: ...

    def set_incident_state(self, incident_id: str, state: WorkflowState) -> Incident: ...

    def append_workflow_event(
        self,
        incident_id: str,
        from_state: WorkflowState | None,
        to_state: WorkflowState,
        trigger: str,
    ) -> WorkflowEvent: ...

    def list_workflow_events(self, incident_id: str) -> list[WorkflowEvent]: ...

    def add_evidence(self, item: EvidenceItem) -> EvidenceItem: ...

    def list_evidence(self, incident_id: str) -> list[EvidenceItem]: ...

    def add_timeline_event(self, event: TimelineEvent) -> TimelineEvent: ...

    def list_timeline(self, incident_id: str) -> list[TimelineEvent]: ...

    def add_hypothesis(self, hypothesis: Hypothesis) -> Hypothesis: ...

    def list_hypotheses(self, incident_id: str) -> list[Hypothesis]: ...

    def add_investigation_report(self, report: InvestigationReport) -> InvestigationReport: ...

    def get_investigation_report(self, incident_id: str) -> InvestigationReport | None: ...

    def add_plan(self, plan: RemediationPlan) -> RemediationPlan: ...

    def list_plans(self, incident_id: str) -> list[RemediationPlan]: ...

    def add_plan_artifact(self, artifact: RemediationPlanArtifact) -> RemediationPlanArtifact: ...

    def get_latest_plan_artifact(self, incident_id: str) -> RemediationPlanArtifact | None: ...

    def list_plan_artifacts(self, incident_id: str) -> list[RemediationPlanArtifact]: ...

    def add_patch(self, patch: PatchAttempt) -> PatchAttempt: ...

    def add_patch_execution(self, artifact: PatchExecutionArtifact) -> PatchExecutionArtifact: ...

    def list_patch_executions(self, incident_id: str) -> list[PatchExecutionArtifact]: ...

    def list_patches(self, incident_id: str) -> list[PatchAttempt]: ...

    def add_verification(self, incident_id: str, run: VerificationRun) -> VerificationRun: ...

    def list_verifications(self, incident_id: str) -> list[VerificationRun]: ...

    def add_verification_artifact(
        self, artifact: VerificationRunArtifact
    ) -> VerificationRunArtifact: ...

    def list_verification_artifacts(self, incident_id: str) -> list[VerificationRunArtifact]: ...

    def get_verification_artifact_for_patch(
        self, patch_id: str
    ) -> VerificationRunArtifact | None: ...

    def add_approval(self, approval: ApprovalRequest) -> ApprovalRequest: ...

    def get_approval(self, approval_id: str) -> ApprovalRequest: ...

    def update_approval(self, approval: ApprovalRequest) -> ApprovalRequest: ...

    def list_approvals(self, incident_id: str) -> list[ApprovalRequest]: ...

    def add_approval_binding(self, binding: ApprovalBinding) -> ApprovalBinding: ...

    def get_approval_binding(self, approval_id: str) -> ApprovalBinding | None: ...

    def add_external_action(self, action: ExternalAction) -> ExternalAction: ...

    def get_external_action(self, action_id: str) -> ExternalAction: ...

    def get_external_action_by_idempotency_key(
        self, idempotency_key: str
    ) -> ExternalAction | None: ...

    def update_external_action(self, action: ExternalAction) -> ExternalAction: ...

    def list_external_actions(self, incident_id: str) -> list[ExternalAction]: ...

    def add_postmortem(self, postmortem: Postmortem) -> Postmortem: ...

    def get_postmortem(self, incident_id: str) -> Postmortem | None: ...

    def add_communications(self, comms: CommunicationUpdate) -> CommunicationUpdate: ...

    def get_communications(self, incident_id: str) -> CommunicationUpdate | None: ...


