"""Initial schema

Revision ID: 114eaeeb8f04
Revises: 
Create Date: 2026-07-12 01:36:51.872045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '114eaeeb8f04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('provider_mode', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.String(length=100), nullable=False),
    sa.Column('approval_type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=2000), nullable=False),
    sa.Column('artifact_version', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_incident_id'), 'approval_requests', ['incident_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('redaction_applied', sa.Boolean(), nullable=False),
    sa.Column('provenance', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_incident_id'), 'evidence_items', ['incident_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.String(length=100), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('supporting_evidence_ids', sqlite.JSON(), nullable=False),
    sa.Column('contradictions', sqlite.JSON(), nullable=False),
    sa.Column('unknowns', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_incident_id'), 'hypotheses', ['incident_id'], unique=False)
    op.create_table('workflow_events',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.String(length=100), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(length=50), nullable=True),
    sa.Column('to_state', sa.String(length=50), nullable=False),
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_events_incident_id'), 'workflow_events', ['incident_id'], unique=False)
    op.create_table('remediation_plans',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.String(length=100), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('steps', sqlite.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('max_files_changed', sa.Integer(), nullable=False),
    sa.Column('max_lines_changed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_plans_incident_id'), 'remediation_plans', ['incident_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.String(length=100), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('evidence_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_incident_id'), 'timeline_events', ['incident_id'], unique=False)
    op.create_table('patch_attempts',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.String(length=100), nullable=False),
    sa.Column('plan_id', sa.String(length=100), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('diff', sa.String(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('lines_changed', sa.Integer(), nullable=False),
    sa.Column('provider_mode', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['remediation_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patch_attempts_incident_id'), 'patch_attempts', ['incident_id'], unique=False)
    op.create_table('verification_runs',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('patch_id', sa.String(length=100), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('checks', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['patch_attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_runs_patch_id'), 'verification_runs', ['patch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_runs_patch_id'), table_name='verification_runs')
    op.drop_table('verification_runs')
    op.drop_index(op.f('ix_patch_attempts_incident_id'), table_name='patch_attempts')
    op.drop_table('patch_attempts')
    op.drop_index(op.f('ix_timeline_events_incident_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_remediation_plans_incident_id'), table_name='remediation_plans')
    op.drop_table('remediation_plans')
    op.drop_index(op.f('ix_workflow_events_incident_id'), table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index(op.f('ix_hypotheses_incident_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_evidence_items_incident_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_approval_requests_incident_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_table('incidents')
    # ### end Alembic commands ###
